# Build environment
FROM node:latest as buildenv

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install


# Build
FROM buildenv as build

WORKDIR /app

COPY . .

RUN npm run build


# Production environment
FROM nginx:latest

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
