version: '2'

services:
  mongodb-dev:
    image: "mongo"
    ports:
      - "27017:27017"
    env_file:
      - "./backend/.env"
    volumes:
      - data-db-dev:/data/db
      - data-configdb-dev:/data/configdb
 
  backend-dev:
    build: 
      context: ./backend/
      dockerfile: Dockerfile-dev
    ports:
      - "6200:6200"
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb-dev

  frontend-dev:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend-dev

volumes:
  data-db-dev:
  data-configdb-dev:
