version: '2'

services:
  mongodb-prod:
    image: "mongo"
    restart: always
    expose:
     - "27017"
    volumes:
     - data-db-prod:/data/db
     - data-configdb-prod:/data/configdb
 
  backend-prod:
    build: 
      context: ./backend/
      dockerfile: Dockerfile-prod
    restart: always
    expose:
      - "6200"
    depends_on:
      - mongodb-prod

  frontend-prod:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-prod

volumes:
  data-db-prod:
  data-configdb-prod:
