version: '2'

services:
  mongodb-dev:
    image: "mongo"
    ports:
      - "27017:27017"
    env_file:
      - "./backend/.env"
    volumes:
      - data-db-dev:/data/db
      - data-configdb-dev:/data/configdb
    networks:
      - dev_default
 
  backend-dev:
    build: 
      context: ./backend/
      dockerfile: Dockerfile-dev
    ports:
      - "6200:6200"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/build
    depends_on:
      - mongodb-dev
    networks:
      - dev_default
  
  frontend-dev:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-dev
    networks:
      - dev_default
  
volumes:
  data-db-dev:
  data-configdb-dev:

networks:
  dev_default:
