# Build environment
FROM node:latest as build

WORKDIR /usr/src/app

COPY package.json .
RUN npm install
RUN npm run build

# Production environment
FROM build

WORKDIR /usr/src/app

COPY . .

EXPOSE 6200

ENV NODE_ENV production

CMD [ "npm", "start" ]
