FROM node:latest

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

EXPOSE 6200

ENV TSC_WATCHFILE UseFsEventsWithFallbackDynamicPolling
ENV TSC_WATCHDIRECTORY RecursiveDirectoryUsingDynamicPriorityPolling
ENV NODE_ENV development

CMD [ "npm", "run", "watch" ]
